version: "3.8"
services:

  kafka:
    image: "bitnami/kafka:3.4.0"
    container_name: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=page-views:3:1
      - KAFKA_ENABLE_KRAFT=yes
    ports:
      - "9092:9092"
  python-wrapper:
    depends_on:
      - kafka
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOOTSTRAP_SERVER=kafka:9092
